### ISSUE TITLE
Unable to build the application

### ISSUE THREAD

**Issue by pazos** [Rain92/UltimateMangaReader#1]
@Rain92 : Hey, thanks for your work. I'd like to contribute back and maybe develop some other qt app for kobo. I built qt 4.8.5 as in your mobileread post without issue but have problems building the application.

I want to double check if you built vlasovsoft free yourself as I found a lot of undefined references to VirtualKeyboard,  QWSPlatform and others.

Could you please elaborate a little bit more on prerequisites for building the application?
Thanks

**Comment by Rain92** [comment]
Hey @pazos cool that you are interested.

To build the mangareader for kobo you only have to make sure you have the source of the app launcher (https://bitbucket.org/vlasovsoft/free) in the same directory. Also make the directory it is called free and not free-master so the path matches the include in the UltimateMangaReader.pro file. You also have to build the 'common' subproject of the launcher and again make sure the path for -lcommon matches in the project file.
To build the common subproject you probably have to add 
CONFIG+=kobo
to the common.pro file or to your build options.

**Comment by Svahnen** [comment]
Im stuck here, what i dont understand is this line:
LIBS  += -L../build-free-Kobo-Release/common -lcommon

Am i supposed to build something and place it in yet another folder named build-free-Kobo-Release? In that case what? i tried to place my newly built "libcommon.a" there, but that was a no go.

What i have done so far is:
cd /home/username/free/common
qmake common.pro
make
cd cd /home/username/UltimateMangaReader
qmake UltimateMangaReader.pro
make

Then i get the same error spoken of above ( error: ‘getVirtualKeyboard’ was not declared in this scope).

Also building the common subproject with "CONFIG+=kobo" gives me the following error: "WARNING: Failure to find: resources/gadget/gadget.qrc", but i get no error without.
