### ISSUE TITLE
Input not working on Libra h2o

### ISSUE THREAD

**Issue by st40611** [Rain92/UltimateMangaReader#10]
Installed KFMon and was able to launch ultimatemangareader.png successfully, and I am presented with a UI, but none of the input works. I can still lock the screen and so I think the device is still functioning - but without input I can't do anything. When I unlock the screen, I will see a "Connecting to Wifi" screen, and then it goes away. End up with a soft reboot instead to get back to normal.

**Comment by st40611** [comment]
Running Software 4.21.15015

KOreader and Plato boots up fine, so I am pretty sure KFMon is installed correctly.

**Comment by gYonder** [comment]
It’s the same on Kobo glo, however I’ve noticed it’s only the touch buttons that don’t work. Lists work and icons seem to work somewhat

**Comment by SalSuleman** [comment]
same issue here on a kobo aura

**Comment by TunaTsuna** [comment]
Same issue. Is there an issue between QT and QT5 Kobo plugin?

**Comment by bangedorrunt** [comment]
same here on kobo libra

**Comment by litori** [comment]
Did anyone manage to get it to work with kobo libra h2o?  I am having the same issue where the screen is non-responsive to touch and any settings I've tried does not work.  Any help would be appreciated.  Thank you.

**Comment by FinleyVickers** [comment]
I'm getting the same error on my libra

**Comment by seajaysec** [comment]
Same here. Looking forward to using it when the Libra's supported. Also, happy to assist with any QA/testing along the road to making that happen.

**Comment by grabercn** [comment]
I managed to temporarily fix this by changing the default line to this in the ultimatemangareader.sh

export QT_QPA_PLATFORM=kobo:touchscreen_rotate=auto:touchscreen_invert_x=1:touchscreen_invert_y=1:logicaldpitarget=108

**Comment by st40611** [comment]
Looks like with 2.5+ version now, this works on Libra H2O ... well, with some changes on the config.

Changing the .sh config to use:

```
export QT_QPA_PLATFORM=kobo:touchscreen_rotate=90:touchscreen_invert_x=0:touchscreen_invert_y=0:logicaldpitarget=300

echo 0 > /sys/class/graphics/fb0/rotate
```

And now this works for me in portrait mode. Thanks!

**Comment by MagikarpLaCarpe** [comment]
Try
https://github.com/Rain92/UltimateMangaReader/issues/10#issuecomment-782843394
