### ISSUE TITLE
Aura HD touchscreen offset

### ISSUE THREAD

**Issue by gaetan-petit** [Rain92/UltimateMangaReader#11]
In order to get the touchscreen in the right orientation I had to set `touchscreen_rotate=90`

Now there's a slight offset in the touchscreen input. In the virtual keyboard hitting W is actually hitting B.
Top and left screen border could not be click, like the upper left menu Icon, the first website icon, or the first keyboard column.

@Rain92 could you advise any way to fix this? Should I mess with the `logicaldpitarget` option?

**Comment by OpenNingia** [comment]
Same issue here. Any advice is apreciated!
