### ISSUE TITLE
[Feature request] double tap to zoom

### ISSUE THREAD

**Issue by webuniverseio** [Rain92/UltimateMangaReader#2]
First of all, thanks for the app! It works great. Sometimes images have very tiny text so it would be great to add double tap to zoom feature similar to how epub files can zoom in when you double tap & zoom out when you double tap again.

**Comment by grabercn** [comment]
I would also appreciate this @Rain92

**Comment by webuniverseio** [comment]
@chrismslist take a look at onyxboox devices. They are fantastic, you can do whatever and have a great manga experience

**Comment by webuniverseio** [comment]
Given that this ticket is 2 years old it is unlikely that anything will happen. Last time I checked this app was not working well, manga resources were obsolete.
