### ISSUE TITLE
Settings page is cut off and cant be scrolled down KOBO Aura second gen

### ISSUE THREAD

**Issue by Svahnen** [Rain92/UltimateMangaReader#22]
On my KOBO Aura second gen when I enter settings, the page is cut off at the bottom, right under where I can select the "Tab" option that can invert page flipping. I can see no button for accepting the changes I make, scrolling the page down or going back from the settings page, it still works to change settings however, and the way I have to exit the settings page is by putting my KOBO to sleep and waking it up again.

**Comment by Svahnen** [comment]
Using latest build 2.5.0 beta

**Comment by Rain92** [comment]
Thanks for the report!
 It's fixed with the latest commit.
BTW you can also exit the settings by clicking on the area outside of the dialog box.
