### ISSUE TITLE
[Mangadex] Titles cut off at apostrophe

### ISSUE THREAD

**Issue by nichobi** [Rain92/UltimateMangaReader#23]
Manga titles from Mangadex have their titles cut off when there's an apostrophe in the name.
All parts of "JoJo's Bizarre Adventure" -> "JoJo"
"Dead Dead Demon's Dededededestruction" -> "Dead Dead Demon"

![IMG_20210112_094312](https://user-images.githubusercontent.com/23172481/104290563-c888f080-54ba-11eb-84bb-ba941cccf20b.jpg)

Using 2.5.0 beta on a Kobo Clara HD (generally works pretty great, thank you so much for your work!)

**Comment by Rain92** [comment]
Thanks! Its fixed in the latest commit.
