### ISSUE TITLE
Double page spreads do not work correctly

### ISSUE THREAD

**Issue by Fivefold** [Rain92/UltimateMangaReader#26]
I have both an Aura ONE and a Clara HD.

Depending on the device, double page spreads are either shrank to fit the screen horizontally (which is okay, but can make text hard to read) or they are expanded to fit it vertically (cutting off the sides). The Clara HD shrinks the image, the Aura ONE expands it. 
**The setting "Show double pages in portrait mode" has no effect on either device.** 

See this [picture ](https://imgur.com/a/Zhk69Dl) to see what I mean. If useful, the page is chapter 13, page 9 from the manga "GTO" hosted on MangaDex.

This happens on the current 2.8.0 release. I did not test any other releases.

**Comment by Rain92** [comment]
Thanks for the report! I can reproduce the problem.
The  double pages in portrait mode setting will only influence newly downloaded pages. So when testing it you have to do clear cache first.

**Comment by Rain92** [comment]
Fixed in latest release
