### ISSUE TITLE
2 page spread 180° turn?

### ISSUE THREAD

**Issue by digitaldiatribe** [Rain92/UltimateMangaReader#27]
Hey there, solid app but I had a question regarding the presentation of 2 pages spreads.

Is there a setting or a line in the script I can change to allow for 2 page spreads to be flipped? I'm on a Forma and I normally read with the buttons on the right when reading in portrait but when the reader presents a 2 page spread in landscape, it's oriented with the buttons at the top, I'm used to and much prefer the reverse of this where the buttons are at the bottom.

Thanks in advance!

**Comment by Rain92** [comment]
I see. I can add that option for the next release.
