### ISSUE TITLE
Mangadex v5 API

### ISSUE THREAD

**Issue by nichobi** [Rain92/UltimateMangaReader#34]
Mangadex has been down for a couple of weeks after a security breach, but has now opened a new (limited) public API for testing. As far as I can tell, it should have all the functionality required for UltimateMangaReader.

[API documentation](https://api.mangadex.org/docs.html)
[Twitter thread](https://twitter.com/MangaDex/status/1390111453827436546)

**Comment by grabercn** [comment]
we really need this, mangadex won't work for me right now. Also they just recently put it back up. I think it would cool if they could intergrate the API further, like better chapter lists and read progress, bookmarks, etc using the API.

**Comment by Rain92** [comment]
Implemented with the latest release
