### ISSUE TITLE
[Bug] UMR crashes when resizing white pages

### ISSUE THREAD

**Issue by azycat** [Rain92/UltimateMangaReader#35]
Hello,

UMR crashes when loading completely white pages of certain mangas. It occurs when reading the manga online and also during download.

I have been able to replicate this problem on two mangas. "Tsukihime" (page ~33, end of chapter 1 beginning of chapter 2) and "Tsukiatte agetemo ii ka na" (page 2).*** I tried reading from multiple sources: MangaHub, MangaPanda, MangaPlus.

***These pages happen to be completely white pages.

I looked at the logfile and it seems to be crashing when the ReSizeBilinear function is applied to these completely white pages. I noticed there's an option in the settings that removes white margins. When I disabled that option, these pages are able to load just fine. So I think that it is crashing because the function is trying to remove the entire white page lol.

I've attached the log file for when it crashes on page ~33ish of Tsukihime. It's not a huge deal honestly since it works perfectly fine when the option is disabled, but I thought it might be useful for you to know that this issue exists.

[log.txt](https://github.com/Rain92/UltimateMangaReader/files/6550367/log.txt)

Have a nice day.

**Comment by Rain92** [comment]
Thanks, fixed in the latest release.
