### ISSUE TITLE
[Issue] Mangadex Not Working!

### ISSUE THREAD

**Issue by grabercn** [Rain92/UltimateMangaReader#37]
When I click on the mangadex source, it gives me a 'could not parse mangainfos' error. This is probably becuase Mangadex currently has a new API (#34) and as such their URL formatting is a bit different now. Because of this, Mangadex does not work on the application. It would be awesome if this could get fixed because mangadex is the best source on here. @Rain92

**Comment by AnnoyedDev** [comment]
There is a new API. wait until RAIN update it :)

**Comment by Rain92** [comment]
Implemented with the latest release
