### ISSUE TITLE
MangaDex not functional

### ISSUE THREAD

**Issue by grabercn** [Rain92/UltimateMangaReader#48]
When trying to access any manga on the mangadex source, I get the error 'cannot parse mangainfos'. This makes mangadex unusable, and should be fixed if people want to access mangadex again using your application.  @Rain92

**Comment by AnnoyedDev** [comment]
My pull request has been merged, Mangadex work again, check the last release @chrismslist

**Comment by grabercn** [comment]
Appreciate it!
