### ISSUE TITLE
[Bug] UltimateMangaReader crash when opening any manga

### ISSUE THREAD

**Issue by LucaSilva-r** [Rain92/UltimateMangaReader#57]
As the title says, whenever i try to open a manga the screen blanks and on the bottom it says KFmon initialized.
I tried using an older version but it didn't fix the issue.

My device is a Libre h2o

**Comment by AnnoyedDev** [comment]
Wich FW version are you using ?

**Comment by LucaSilva-r** [comment]
Right now I'm on firmware 4.32.19501

**Comment by LucaSilva-r** [comment]
update:
I downgraded the firmware to 4.28 and it still happens. 
I think the problem is due to the fact that I'm forced to use a different version of the qt library at this point.

**Comment by AnnoyedDev** [comment]
You may need to manually delete / rename the cache folder, it can happen sometimes

**Comment by LucaSilva-r** [comment]
i tried it but unfortunately still crashes. 
Right now I'm using kfmon 1.4.5 with the latest nickelmenu.
Maybe i missed something during the installation?

**Comment by AnnoyedDev** [comment]
I have another friend who have a libra h2o and he is facing a lot of problem too.. Hmm i don't have any solution at this moment sadly. I know there is some problem with the screen size detection.
Please, post your log.txt inside the folder of the app.

**Comment by LucaSilva-r** [comment]
Ok the log says it fails to save the thumbnail.  And then looks like it fails when resizing the image? Kind of?
[log.txt](https://github.com/Rain92/UltimateMangaReader/files/8699685/log.txt)

**Comment by AnnoyedDev** [comment]
It's seem there is a lot of problem with a lot of people with the resize

`void Simd::Neon::ResizeBilinear`
`../UltimateMangaReader-Qt5/thirdparty/simdimageresize.cpp:389: void Simd::Neon::ResizeBilinear(const uint8_t*, size_t, size_t, size_t, uint8_t*, size_t, size_t, size_t) [with unsigned int channelCount = 1; uint8_t = unsigned char; size_t = unsigned int]: Assertion `dstWidth >= A' failed.`


I have some friend who have the same problem and error with h2o. However i do not have any problem with my kobo forma. i do not know how to fix that but i know that the `screensize` in the `imageprocessingnative.cpp` return a 0 pixel height wich result in simdimageresizer to crash.

**Comment by LucaSilva-r** [comment]
What about just commenting out the assert ? 
i tried setting up all the tool chain put I got stuck unfortunately.

if I could I would try to just remove that

**Comment by AnnoyedDev** [comment]
It is not possible because it would make the image way too large or way too small, i have already done a temp fix for one user in my fork, but it does not solve the problem, instead it make the image sometimes too small, sometimes too big, and it is a per-user workaround wich is impraticable in real conditions.

I do not think i have enough knowledge to fix that, but what i can tell for the original dev  is it happen on h2o, on clara hd but NOT on the kobo forma.

for some user, chaning the version of the qt folder (by downloading older version) fixe the problem but create another (no touch working, still crashing etc).
![](https://user-images.githubusercontent.com/35310573/168654858-5e7150f5-8a9a-4c29-922c-d0d5e48163b9.png)

**Comment by LucaSilva-r** [comment]
I understand. But I'd still like to give it a shot with the basic knowledge I have.
Only issue I have is setting up the toolchain. Particularly the SYSROOT parameter. What should it be ?

Sorry for bothering you!

Having the app working is not a problem, it's a challenge now

**Comment by AnnoyedDev** [comment]
sysroot is the system root of the arm built system

**Comment by LucaSilva-r** [comment]
Latest version fixes everything
