### ISSUE TITLE
Mangadex cannot load pages

### ISSUE THREAD

**Issue by grabercn** [Rain92/UltimateMangaReader#66]
When clicking a manga under the mangadex source, it appears mangadex cannot load the pages. I keep getting a timeout error.
@Rain92 
Thanks

**Comment by skyqrose** [comment]
[The release notes for v2.17.1](https://github.com/Rain92/UltimateMangaReader/releases/tag/2.17.2) on Nov 2 says it [fixed some mangadex issues](https://github.com/Rain92/UltimateMangaReader/commit/b238600063eaa774bce8c41f4f8b84425ab39caa).
